# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 07:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='start_date',
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.CharField(default=datetime.datetime(2016, 6, 17, 7, 12, 44, 741850, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.CharField(default=datetime.datetime(2016, 6, 17, 7, 12, 49, 12223, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='summer_course',
            field=models.CharField(max_length=5),
        ),
    ]
