# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Mentor'),
        ),
    ]
