# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20160617_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='plan_after_eight',
            field=models.TextField(blank=True, null=True),
        ),
    ]
