# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_team_leader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('projects', models.ManyToManyField(to='projects.Project')),
            ],
        ),
    ]
