# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20160626_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='projects',
            field=models.ManyToManyField(blank=True, to='projects.Project'),
        ),
    ]
